steps:
  # 1. Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/smartflood-v3.2/smartflood-api:$COMMIT_SHA'
      - '-f'
      - 'Backend/api/Dockerfile'
      - '.'

  # 2. Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/smartflood-v3.2/smartflood-api:$COMMIT_SHA'

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'smartflood-api'
      - '--image'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/smartflood-v3.2/smartflood-api:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--port'
      - '5000'

images:
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/smartflood-v3.2/smartflood-api:$COMMIT_SHA'
