import { downloadPdfReport, type PdfReportSection } from "@/lib/pdfReport";
import type { ReliefBarangayBreakdown, ReliefCampaign, ReliefDistributionRecord, ReliefReportSummary } from "@/types/emergency";

type DownloadReliefHistoryReportInput = {
  campaign: ReliefCampaign;
  history: ReliefDistributionRecord[];
  summary?: ReliefReportSummary | null;
  barangays?: ReliefBarangayBreakdown[];
  scopeLabel: string;
  generatedBy?: string;
};

export function downloadReliefHistoryReport({
  barangays = [],
  campaign,
  generatedBy,
  history,
  scopeLabel,
  summary,
}: DownloadReliefHistoryReportInput) {
  const generatedAt = new Date();
  const title = "SmartFlood Historical Distribution Report";
  const sections: PdfReportSection[] = [
    {
      kind: "paragraph",
      text: "This formal report summarizes campaign-scoped relief distribution history using the current dashboard access scope. It includes operational summary data and confirmed receipt records only.",
    },
    {
      kind: "details",
      rows: [
        ["Relief Program", campaign.plan_name],
        ["Strategy", formatReportStatus(campaign.plan_id)],
        ["Campaign Status", formatReportStatus(campaign.status)],
        ["Operational Scope", scopeLabel],
        ["Started", formatReportDate(campaign.started_at ?? campaign.accepted_at ?? campaign.created_at)],
        ["Closed / Expiration", formatReportDate(campaign.closed_at ?? campaign.expires_at)],
        ["Generated At", formatReportDate(generatedAt.toISOString())],
        ["Generated By", generatedBy || "SmartFlood dashboard"],
      ],
    },
  ];

  if (summary) {
    sections.push({
      kind: "heading",
      text: "Campaign Summary",
    });
    sections.push({
      kind: "details",
      rows: [
        ["Barangays", summary.barangays],
        ["Eligible Families", summary.eligible],
        ["Received", summary.received],
        ["Not Received", summary.not_received],
        ["Coverage", `${summary.coverage}%`],
      ],
    });
  } else {
    const received = history.filter((record) => record.status === "received").length;
    sections.push({
      kind: "heading",
      text: "Campaign Summary",
    });
    sections.push({
      kind: "details",
      rows: [
        ["Confirmed Receipt Records", history.length],
        ["Received", received],
        ["Other Statuses", Math.max(0, history.length - received)],
      ],
    });
  }

  if (barangays.length > 0) {
    sections.push({
      kind: "table",
      title: "Barangay Coverage",
      table: {
        headers: ["Barangay", "Eligible", "Received", "Not Received", "Coverage"],
        rows: barangays.map((row) => [
          row.barangay_name,
          row.eligible,
          row.received,
          row.not_received,
          `${row.coverage}%`,
        ]),
      },
    });
  }

  sections.push({
    kind: "table",
    title: "Distribution History",
    table: {
      headers: ["Family", "Family Head", "Barangay", "Status", "Received At", "Verified By"],
      rows: history.length > 0
        ? history.map((record) => [
          record.family_name ?? "Family",
          record.family_head_name ?? "Not recorded",
          record.barangay_name ?? `Barangay ${record.barangay_id}`,
          formatReportStatus(record.status),
          formatReportDate(record.verified_at),
          record.verified_by_name ?? "Not recorded",
        ])
        : [["No confirmed distribution history records for this campaign.", "", "", "", "", ""]],
    },
  });

  downloadPdfReport(`${filenamePart(campaign.plan_name)}-history-report-${filenameDate(generatedAt)}.pdf`, title, sections);
}

export function formatReportDate(value?: string | null) {
  if (!value) return "Not recorded";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return String(value);
  return new Intl.DateTimeFormat("en", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
  }).format(date);
}

export function formatReportStatus(value?: string | null) {
  const text = String(value ?? "").replace(/_/g, " ").trim();
  return text ? text.replace(/\b\w/g, (char) => char.toUpperCase()) : "Unknown";
}

function filenamePart(value: string) {
  return value.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "smartflood";
}

function filenameDate(value: Date) {
  return value.toISOString().slice(0, 10);
}
